// Users
export const USERS = [
  { id: "u1", username: "SpookyWarrior", email: "warrior@haunted.com", password: "warrior123" },
  { id: "u2", username: "ShadowMage", email: "mage@darkness.com", password: "shadow123" },
  { id: "u3", username: "PhantomRogue", email: "rogue@phantom.com", password: "phantom123" },
  { id: "u4", username: "GhostKnight", email: "knight@spectral.com", password: "ghost123" },
  { id: "u5", username: "IronCleric", email: "cleric@forge.com", password: "iron123" },
  { id: "u6", username: "SilverArcher", email: "archer@silver.com", password: "silver123" },
  { id: "u7", username: "CrimsonPaladin", email: "paladin@crimson.com", password: "crim123" },
  { id: "u8", username: "AzureSorcerer", email: "sorcerer@azure.com", password: "azure123" },
  { id: "u9", username: "VerdantDruid", email: "druid@verdant.com", password: "verdant123" },
  { id: "u10", username: "BronzeRanger", email: "ranger@bronze.com", password: "bronze123" },
];

// Items
export const ITEMS = [
  { id: 1, name: "Minor Health Potion" },
  { id: 2, name: "Broken Straight Sword" },
  { id: 3, name: "A rusted nail" },
  { id: 4, name: "An all-seeing eyeball" },
  { id: 5, name: "A jar of the ghosts of your past" },
  { id: 6, name: "The claw of a three-winged heron" },
  { id: 7, name: "The heart of a siren" },
  { id: 8, name: "A B.F sword" },
  { id: 9, name: "A feather from a fallen angel" },
  { id: 10, name: "The key to the universe" },
];

// Items for each user
export const USER_ITEMS = [
  { userId: "u1", itemId: 1 },
  { userId: "u1", itemId: 2 },
  { userId: "u2", itemId: 3 },
  { userId: "u2", itemId: 4 },
  { userId: "u3", itemId: 5 },
  { userId: "u3", itemId: 6 },
  { userId: "u4", itemId: 7 },
  { userId: "u4", itemId: 8 },
  { userId: "u5", itemId: 9 },
  { userId: "u5", itemId: 10 },
  { userId: "u6", itemId: 1 },
  { userId: "u6", itemId: 3 },
  { userId: "u7", itemId: 2 },
  { userId: "u7", itemId: 5 },
  { userId: "u8", itemId: 4 },
  { userId: "u8", itemId: 6 },
  { userId: "u9", itemId: 7 },
  { userId: "u9", itemId: 9 },
  { userId: "u10", itemId: 8 },
  { userId: "u10", itemId: 10 },
];

// Battle log msgs (id is autogenerated)
export const BATTLE_LOG_MESSAGES = [
  { type: "system", text: "Battle has begun!", timestamp: new Date("2026-02-24T10:00:00"), userId: "u1" },
  { type: "ally", text: "You draw your sword and prepare for combat.", timestamp: new Date("2026-02-24T10:00:05"), userId: "u1" },
  { type: "enemy", text: "The goblin snarls and charges toward you!", timestamp: new Date("2026-02-24T10:00:08"), userId: "u1" },
  { type: "ally", text: "You strike the enemy with your sword!", timestamp: new Date("2026-02-24T10:00:12"), userId: "u1" },
  { type: "enemy", text: "The enemy takes 15 damage!", timestamp: new Date("2026-02-24T10:00:13"), userId: "u1" },
  { type: "ally", text: "You cast Fireball on the enemy!", timestamp: new Date("2026-02-24T10:00:18"), userId: "u1" },
  { type: "enemy", text: "The enemy is engulfed in flames! 25 damage!", timestamp: new Date("2026-02-24T10:00:19"), userId: "u1" },
  { type: "enemy", text: "The goblin swings its rusty blade at you!", timestamp: new Date("2026-02-24T10:00:22"), userId: "u1" },
  { type: "system", text: "You blocked the attack!", timestamp: new Date("2026-02-24T10:00:23"), userId: "u1" },
  { type: "ally", text: "You raise your shield in defense.", timestamp: new Date("2026-02-24T10:00:27"), userId: "u1" },
];